version: '3.8'

services:
  backend:
    image: ghcr.io/ar00n/alpr-rust/backend:latest
    # ports:
    #   - "3000:3000"
    expose:
      - "3000"
    environment:
      - ENABLE_CUDA=${ENABLE_CUDA:-false}
      - ENABLE_OPENVINO=${ENABLE_OPENVINO:-false}
    volumes:
      # Persist the SQLite database outside the container
      - backend_data:/app/data
      - backend_snapshots:/app/snapshots

  frontend:
    image: ghcr.io/ar00n/alpr-rust/backend:latest
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  backend_data:
  backend_snapshots: