version: '3.8'

services:
  backend:
    image: ghcr.io/ar00n/alpr-rust/backend:latest
    restart: unless-stopped
    # ports:
    #   - "3000:3000"
    expose:
      - "3000"
    environment:
      - ENABLE_CUDA=${ENABLE_CUDA:-false}
      - ENABLE_OPENVINO=${ENABLE_OPENVINO:-false}
    volumes:
      # Persist the SQLite database outside the container
      - backend_data:/app/data
      - backend_snapshots:/app/snapshots

  frontend:
    image: ghcr.io/ar00n/alpr-rust/frontend:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate --protocol quic run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TOKEN}

  watchtower:
    image: containrrr/watchtower:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true # Deletes old images after updating
      - WATCHTOWER_POLL_INTERVAL=86400 # Checks for updates every 24 hours (in seconds)

volumes:
  backend_data:
  backend_snapshots: