/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * alpr_backend
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customAxios } from './custom-axios';
export interface AllowListEntry {
  /** @nullable */
  expiry_date?: string | null;
  plate: string;
}

export interface AppErrorResponse {
  error: string;
}

export interface ChangePasswordPayload {
  new_password: string;
}

export interface CreateCustomAction {
  /** Sensitive credentials (e.g., {"username": "admin", "password": "123"}) */
  auth_data?: unknown;
  auth_type: string;
  /** @nullable */
  body_template?: string | null;
  /** @nullable */
  delay_seconds?: number | null;
  /** Optional custom headers */
  headers?: unknown;
  method: string;
  name: string;
  url: string;
}

export interface CreateUserPayload {
  is_admin: boolean;
  password: string;
  username: string;
}

export interface CustomActionResponse {
  auth_type: string;
  /** @nullable */
  body_template?: string | null;
  /** @nullable */
  delay_seconds?: number | null;
  headers?: unknown;
  id: number;
  method: string;
  name: string;
  url: string;
}

export interface LoginResponse {
  token: string;
}

export interface PlateRead {
  confidence: number;
  /** @nullable */
  id?: number | null;
  plate: string;
  /** @nullable */
  snapshot_image?: string | null;
  timestamp: string;
  was_allowed: boolean;
}

export interface PaginatedHistoryResponse {
  items: PlateRead[];
  /** @minimum 0 */
  page: number;
  /** @minimum 0 */
  per_page: number;
  total: number;
  /** @minimum 0 */
  total_pages: number;
}

export interface TestActionResponse {
  body: string;
  /** @minimum 0 */
  status: number;
}

export interface UpdateFrameratePayload {
  /** @minimum 0 */
  framerate: number;
}

export interface UpdateMinConfidencePayload {
  min_confidence: number;
}

export interface UpdateRTSPUrlPayload {
  /** @nullable */
  rtsp_url?: string | null;
}

export interface UpdateTrimHistoryPayload {
  /**
     * @minimum 0
     * @nullable
     */
  trim_history_days?: number | null;
}

export interface UpdateTrimSnapshotsPayload {
  /**
     * @minimum 0
     * @nullable
     */
  trim_snapshots_mb?: number | null;
}

export interface UserLoginRequest {
  password: string;
  username: string;
}

export interface UserResponse {
  id: number;
  is_admin: boolean;
  username: string;
}

export type GetHistoryHandlerParams = {
/**
 * @minimum 0
 */
page?: number;
/**
 * @minimum 0
 */
per_page?: number;
plate?: string;
};

export type UpdateFramerate200 = { [key: string]: unknown };

export type UpdateMinConfidence200 = { [key: string]: unknown };

export type UpdateRtspUrl200 = { [key: string]: unknown };

export type UpdateTrimHistory200 = { [key: string]: unknown };

export type UpdateTrimSnapshots200 = { [key: string]: unknown };

export type WebsocketHandlerParams = {
/**
 * JWT Bearer Token for WebSocket Auth
 */
token: string;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getAllowList = (

 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {


      return customAxios<AllowListEntry[]>(
      {url: `/api/allow-list`, method: 'GET', signal
    },
      options);
    }




export const getGetAllowListQueryKey = () => {
    return [
    `/api/allow-list`
    ] as const;
    }


export const getGetAllowListQueryOptions = <TData = Awaited<ReturnType<typeof getAllowList>>, TError = AppErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllowList>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllowListQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllowList>>> = ({ signal }) => getAllowList(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllowList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllowListQueryResult = NonNullable<Awaited<ReturnType<typeof getAllowList>>>
export type GetAllowListQueryError = AppErrorResponse


export function useGetAllowList<TData = Awaited<ReturnType<typeof getAllowList>>, TError = AppErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllowList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllowList>>,
          TError,
          Awaited<ReturnType<typeof getAllowList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllowList<TData = Awaited<ReturnType<typeof getAllowList>>, TError = AppErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllowList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllowList>>,
          TError,
          Awaited<ReturnType<typeof getAllowList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllowList<TData = Awaited<ReturnType<typeof getAllowList>>, TError = AppErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllowList>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAllowList<TData = Awaited<ReturnType<typeof getAllowList>>, TError = AppErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllowList>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllowListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const addAllowList = (
    allowListEntry: AllowListEntry,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {


      return customAxios<AllowListEntry>(
      {url: `/api/allow-list`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: allowListEntry, signal
    },
      options);
    }




export const getAddAllowListMutationOptions = <TError = AppErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addAllowList>>, TError,{data: AllowListEntry}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof addAllowList>>, TError,{data: AllowListEntry}, TContext> => {

const mutationKey = ['addAllowList'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addAllowList>>, {data: AllowListEntry}> = (props) => {
          const {data} = props ?? {};

          return  addAllowList(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AddAllowListMutationResult = NonNullable<Awaited<ReturnType<typeof addAllowList>>>
    export type AddAllowListMutationBody = AllowListEntry
    export type AddAllowListMutationError = AppErrorResponse

    export const useAddAllowList = <TError = AppErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addAllowList>>, TError,{data: AllowListEntry}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addAllowList>>,
        TError,
        {data: AllowListEntry},
        TContext
      > => {
      return useMutation(getAddAllowListMutationOptions(options), queryClient);
    }

export const deleteAllowList = (
    plate: string,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {


      return customAxios<void>(
      {url: `/api/allow-list/${plate}`, method: 'DELETE', signal
    },
      options);
    }




export const getDeleteAllowListMutationOptions = <TError = AppErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAllowList>>, TError,{plate: string}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAllowList>>, TError,{plate: string}, TContext> => {

const mutationKey = ['deleteAllowList'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAllowList>>, {plate: string}> = (props) => {
          const {plate} = props ?? {};

          return  deleteAllowList(plate,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteAllowListMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAllowList>>>

    export type DeleteAllowListMutationError = AppErrorResponse

    export const useDeleteAllowList = <TError = AppErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAllowList>>, TError,{plate: string}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAllowList>>,
        TError,
        {plate: string},
        TContext
      > => {
      return useMutation(getDeleteAllowListMutationOptions(options), queryClient);
    }

export const loginUser = (
    userLoginRequest: UserLoginRequest,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {


      return customAxios<LoginResponse>(
      {url: `/api/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userLoginRequest, signal
    },
      options);
    }




export const getLoginUserMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginUser>>, TError,{data: UserLoginRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof loginUser>>, TError,{data: UserLoginRequest}, TContext> => {

const mutationKey = ['loginUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginUser>>, {data: UserLoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  loginUser(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LoginUserMutationResult = NonNullable<Awaited<ReturnType<typeof loginUser>>>
    export type LoginUserMutationBody = UserLoginRequest
    export type LoginUserMutationError = void

    export const useLoginUser = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginUser>>, TError,{data: UserLoginRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof loginUser>>,
        TError,
        {data: UserLoginRequest},
        TContext
      > => {
      return useMutation(getLoginUserMutationOptions(options), queryClient);
    }

export const getCustomActions = (

 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {


      return customAxios<CustomActionResponse[]>(
      {url: `/api/custom-actions`, method: 'GET', signal
    },
      options);
    }




export const getGetCustomActionsQueryKey = () => {
    return [
    `/api/custom-actions`
    ] as const;
    }


export const getGetCustomActionsQueryOptions = <TData = Awaited<ReturnType<typeof getCustomActions>>, TError = AppErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCustomActions>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCustomActionsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCustomActions>>> = ({ signal }) => getCustomActions(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCustomActions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCustomActionsQueryResult = NonNullable<Awaited<ReturnType<typeof getCustomActions>>>
export type GetCustomActionsQueryError = AppErrorResponse


export function useGetCustomActions<TData = Awaited<ReturnType<typeof getCustomActions>>, TError = AppErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCustomActions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCustomActions>>,
          TError,
          Awaited<ReturnType<typeof getCustomActions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCustomActions<TData = Awaited<ReturnType<typeof getCustomActions>>, TError = AppErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCustomActions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCustomActions>>,
          TError,
          Awaited<ReturnType<typeof getCustomActions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCustomActions<TData = Awaited<ReturnType<typeof getCustomActions>>, TError = AppErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCustomActions>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetCustomActions<TData = Awaited<ReturnType<typeof getCustomActions>>, TError = AppErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCustomActions>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCustomActionsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const addCustomAction = (
    createCustomAction: CreateCustomAction,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {


      return customAxios<CustomActionResponse>(
      {url: `/api/custom-actions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCustomAction, signal
    },
      options);
    }




export const getAddCustomActionMutationOptions = <TError = AppErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addCustomAction>>, TError,{data: CreateCustomAction}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof addCustomAction>>, TError,{data: CreateCustomAction}, TContext> => {

const mutationKey = ['addCustomAction'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addCustomAction>>, {data: CreateCustomAction}> = (props) => {
          const {data} = props ?? {};

          return  addCustomAction(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AddCustomActionMutationResult = NonNullable<Awaited<ReturnType<typeof addCustomAction>>>
    export type AddCustomActionMutationBody = CreateCustomAction
    export type AddCustomActionMutationError = AppErrorResponse

    export const useAddCustomAction = <TError = AppErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addCustomAction>>, TError,{data: CreateCustomAction}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addCustomAction>>,
        TError,
        {data: CreateCustomAction},
        TContext
      > => {
      return useMutation(getAddCustomActionMutationOptions(options), queryClient);
    }

export const testCustomAction = (
    createCustomAction: CreateCustomAction,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {


      return customAxios<TestActionResponse>(
      {url: `/api/custom-actions/test`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCustomAction, signal
    },
      options);
    }




export const getTestCustomActionMutationOptions = <TError = AppErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof testCustomAction>>, TError,{data: CreateCustomAction}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof testCustomAction>>, TError,{data: CreateCustomAction}, TContext> => {

const mutationKey = ['testCustomAction'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof testCustomAction>>, {data: CreateCustomAction}> = (props) => {
          const {data} = props ?? {};

          return  testCustomAction(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TestCustomActionMutationResult = NonNullable<Awaited<ReturnType<typeof testCustomAction>>>
    export type TestCustomActionMutationBody = CreateCustomAction
    export type TestCustomActionMutationError = AppErrorResponse

    export const useTestCustomAction = <TError = AppErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof testCustomAction>>, TError,{data: CreateCustomAction}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof testCustomAction>>,
        TError,
        {data: CreateCustomAction},
        TContext
      > => {
      return useMutation(getTestCustomActionMutationOptions(options), queryClient);
    }

export const deleteCustomAction = (
    id: number,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {


      return customAxios<void>(
      {url: `/api/custom-actions/${id}`, method: 'DELETE', signal
    },
      options);
    }




export const getDeleteCustomActionMutationOptions = <TError = AppErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCustomAction>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCustomAction>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteCustomAction'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCustomAction>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteCustomAction(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteCustomActionMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCustomAction>>>

    export type DeleteCustomActionMutationError = AppErrorResponse

    export const useDeleteCustomAction = <TError = AppErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCustomAction>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCustomAction>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteCustomActionMutationOptions(options), queryClient);
    }

export const getHistoryHandler = (
    params?: GetHistoryHandlerParams,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {


      return customAxios<PaginatedHistoryResponse>(
      {url: `/api/history`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetHistoryHandlerQueryKey = (params?: GetHistoryHandlerParams,) => {
    return [
    `/api/history`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetHistoryHandlerQueryOptions = <TData = Awaited<ReturnType<typeof getHistoryHandler>>, TError = AppErrorResponse>(params?: GetHistoryHandlerParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHistoryHandler>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHistoryHandlerQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHistoryHandler>>> = ({ signal }) => getHistoryHandler(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHistoryHandler>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetHistoryHandlerQueryResult = NonNullable<Awaited<ReturnType<typeof getHistoryHandler>>>
export type GetHistoryHandlerQueryError = AppErrorResponse


export function useGetHistoryHandler<TData = Awaited<ReturnType<typeof getHistoryHandler>>, TError = AppErrorResponse>(
 params: undefined |  GetHistoryHandlerParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHistoryHandler>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHistoryHandler>>,
          TError,
          Awaited<ReturnType<typeof getHistoryHandler>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHistoryHandler<TData = Awaited<ReturnType<typeof getHistoryHandler>>, TError = AppErrorResponse>(
 params?: GetHistoryHandlerParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHistoryHandler>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHistoryHandler>>,
          TError,
          Awaited<ReturnType<typeof getHistoryHandler>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHistoryHandler<TData = Awaited<ReturnType<typeof getHistoryHandler>>, TError = AppErrorResponse>(
 params?: GetHistoryHandlerParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHistoryHandler>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetHistoryHandler<TData = Awaited<ReturnType<typeof getHistoryHandler>>, TError = AppErrorResponse>(
 params?: GetHistoryHandlerParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHistoryHandler>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetHistoryHandlerQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getFramerate = (

 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {


      return customAxios<UpdateFrameratePayload>(
      {url: `/api/settings/framerate`, method: 'GET', signal
    },
      options);
    }




export const getGetFramerateQueryKey = () => {
    return [
    `/api/settings/framerate`
    ] as const;
    }


export const getGetFramerateQueryOptions = <TData = Awaited<ReturnType<typeof getFramerate>>, TError = AppErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFramerate>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFramerateQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFramerate>>> = ({ signal }) => getFramerate(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFramerate>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFramerateQueryResult = NonNullable<Awaited<ReturnType<typeof getFramerate>>>
export type GetFramerateQueryError = AppErrorResponse


export function useGetFramerate<TData = Awaited<ReturnType<typeof getFramerate>>, TError = AppErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFramerate>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFramerate>>,
          TError,
          Awaited<ReturnType<typeof getFramerate>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFramerate<TData = Awaited<ReturnType<typeof getFramerate>>, TError = AppErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFramerate>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFramerate>>,
          TError,
          Awaited<ReturnType<typeof getFramerate>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFramerate<TData = Awaited<ReturnType<typeof getFramerate>>, TError = AppErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFramerate>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetFramerate<TData = Awaited<ReturnType<typeof getFramerate>>, TError = AppErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFramerate>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFramerateQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const updateFramerate = (
    updateFrameratePayload: UpdateFrameratePayload,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {


      return customAxios<UpdateFramerate200>(
      {url: `/api/settings/framerate`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateFrameratePayload, signal
    },
      options);
    }




export const getUpdateFramerateMutationOptions = <TError = AppErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateFramerate>>, TError,{data: UpdateFrameratePayload}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof updateFramerate>>, TError,{data: UpdateFrameratePayload}, TContext> => {

const mutationKey = ['updateFramerate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateFramerate>>, {data: UpdateFrameratePayload}> = (props) => {
          const {data} = props ?? {};

          return  updateFramerate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateFramerateMutationResult = NonNullable<Awaited<ReturnType<typeof updateFramerate>>>
    export type UpdateFramerateMutationBody = UpdateFrameratePayload
    export type UpdateFramerateMutationError = AppErrorResponse

    export const useUpdateFramerate = <TError = AppErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateFramerate>>, TError,{data: UpdateFrameratePayload}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateFramerate>>,
        TError,
        {data: UpdateFrameratePayload},
        TContext
      > => {
      return useMutation(getUpdateFramerateMutationOptions(options), queryClient);
    }

export const getMinConfidence = (

 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {


      return customAxios<UpdateMinConfidencePayload>(
      {url: `/api/settings/min-confidence`, method: 'GET', signal
    },
      options);
    }




export const getGetMinConfidenceQueryKey = () => {
    return [
    `/api/settings/min-confidence`
    ] as const;
    }


export const getGetMinConfidenceQueryOptions = <TData = Awaited<ReturnType<typeof getMinConfidence>>, TError = AppErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMinConfidence>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMinConfidenceQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMinConfidence>>> = ({ signal }) => getMinConfidence(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMinConfidence>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMinConfidenceQueryResult = NonNullable<Awaited<ReturnType<typeof getMinConfidence>>>
export type GetMinConfidenceQueryError = AppErrorResponse


export function useGetMinConfidence<TData = Awaited<ReturnType<typeof getMinConfidence>>, TError = AppErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMinConfidence>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMinConfidence>>,
          TError,
          Awaited<ReturnType<typeof getMinConfidence>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMinConfidence<TData = Awaited<ReturnType<typeof getMinConfidence>>, TError = AppErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMinConfidence>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMinConfidence>>,
          TError,
          Awaited<ReturnType<typeof getMinConfidence>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMinConfidence<TData = Awaited<ReturnType<typeof getMinConfidence>>, TError = AppErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMinConfidence>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetMinConfidence<TData = Awaited<ReturnType<typeof getMinConfidence>>, TError = AppErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMinConfidence>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMinConfidenceQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const updateMinConfidence = (
    updateMinConfidencePayload: UpdateMinConfidencePayload,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {


      return customAxios<UpdateMinConfidence200>(
      {url: `/api/settings/min-confidence`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateMinConfidencePayload, signal
    },
      options);
    }




export const getUpdateMinConfidenceMutationOptions = <TError = AppErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMinConfidence>>, TError,{data: UpdateMinConfidencePayload}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof updateMinConfidence>>, TError,{data: UpdateMinConfidencePayload}, TContext> => {

const mutationKey = ['updateMinConfidence'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMinConfidence>>, {data: UpdateMinConfidencePayload}> = (props) => {
          const {data} = props ?? {};

          return  updateMinConfidence(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateMinConfidenceMutationResult = NonNullable<Awaited<ReturnType<typeof updateMinConfidence>>>
    export type UpdateMinConfidenceMutationBody = UpdateMinConfidencePayload
    export type UpdateMinConfidenceMutationError = AppErrorResponse

    export const useUpdateMinConfidence = <TError = AppErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMinConfidence>>, TError,{data: UpdateMinConfidencePayload}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateMinConfidence>>,
        TError,
        {data: UpdateMinConfidencePayload},
        TContext
      > => {
      return useMutation(getUpdateMinConfidenceMutationOptions(options), queryClient);
    }

export const getRtspUrl = (

 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {


      return customAxios<UpdateRTSPUrlPayload>(
      {url: `/api/settings/rtsp_url`, method: 'GET', signal
    },
      options);
    }




export const getGetRtspUrlQueryKey = () => {
    return [
    `/api/settings/rtsp_url`
    ] as const;
    }


export const getGetRtspUrlQueryOptions = <TData = Awaited<ReturnType<typeof getRtspUrl>>, TError = AppErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRtspUrl>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRtspUrlQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRtspUrl>>> = ({ signal }) => getRtspUrl(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRtspUrl>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRtspUrlQueryResult = NonNullable<Awaited<ReturnType<typeof getRtspUrl>>>
export type GetRtspUrlQueryError = AppErrorResponse


export function useGetRtspUrl<TData = Awaited<ReturnType<typeof getRtspUrl>>, TError = AppErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRtspUrl>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRtspUrl>>,
          TError,
          Awaited<ReturnType<typeof getRtspUrl>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRtspUrl<TData = Awaited<ReturnType<typeof getRtspUrl>>, TError = AppErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRtspUrl>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRtspUrl>>,
          TError,
          Awaited<ReturnType<typeof getRtspUrl>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRtspUrl<TData = Awaited<ReturnType<typeof getRtspUrl>>, TError = AppErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRtspUrl>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetRtspUrl<TData = Awaited<ReturnType<typeof getRtspUrl>>, TError = AppErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRtspUrl>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRtspUrlQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const updateRtspUrl = (
    updateRTSPUrlPayload: UpdateRTSPUrlPayload,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {


      return customAxios<UpdateRtspUrl200>(
      {url: `/api/settings/rtsp_url`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateRTSPUrlPayload, signal
    },
      options);
    }




export const getUpdateRtspUrlMutationOptions = <TError = AppErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRtspUrl>>, TError,{data: UpdateRTSPUrlPayload}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof updateRtspUrl>>, TError,{data: UpdateRTSPUrlPayload}, TContext> => {

const mutationKey = ['updateRtspUrl'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateRtspUrl>>, {data: UpdateRTSPUrlPayload}> = (props) => {
          const {data} = props ?? {};

          return  updateRtspUrl(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateRtspUrlMutationResult = NonNullable<Awaited<ReturnType<typeof updateRtspUrl>>>
    export type UpdateRtspUrlMutationBody = UpdateRTSPUrlPayload
    export type UpdateRtspUrlMutationError = AppErrorResponse

    export const useUpdateRtspUrl = <TError = AppErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRtspUrl>>, TError,{data: UpdateRTSPUrlPayload}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateRtspUrl>>,
        TError,
        {data: UpdateRTSPUrlPayload},
        TContext
      > => {
      return useMutation(getUpdateRtspUrlMutationOptions(options), queryClient);
    }

export const getTrimHistory = (

 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {


      return customAxios<UpdateTrimHistoryPayload>(
      {url: `/api/settings/trim_history`, method: 'GET', signal
    },
      options);
    }




export const getGetTrimHistoryQueryKey = () => {
    return [
    `/api/settings/trim_history`
    ] as const;
    }


export const getGetTrimHistoryQueryOptions = <TData = Awaited<ReturnType<typeof getTrimHistory>>, TError = void | AppErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTrimHistory>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTrimHistoryQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTrimHistory>>> = ({ signal }) => getTrimHistory(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTrimHistory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTrimHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof getTrimHistory>>>
export type GetTrimHistoryQueryError = void | AppErrorResponse


export function useGetTrimHistory<TData = Awaited<ReturnType<typeof getTrimHistory>>, TError = void | AppErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTrimHistory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTrimHistory>>,
          TError,
          Awaited<ReturnType<typeof getTrimHistory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTrimHistory<TData = Awaited<ReturnType<typeof getTrimHistory>>, TError = void | AppErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTrimHistory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTrimHistory>>,
          TError,
          Awaited<ReturnType<typeof getTrimHistory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTrimHistory<TData = Awaited<ReturnType<typeof getTrimHistory>>, TError = void | AppErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTrimHistory>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetTrimHistory<TData = Awaited<ReturnType<typeof getTrimHistory>>, TError = void | AppErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTrimHistory>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTrimHistoryQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const updateTrimHistory = (
    updateTrimHistoryPayload: UpdateTrimHistoryPayload,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {


      return customAxios<UpdateTrimHistory200>(
      {url: `/api/settings/trim_history`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateTrimHistoryPayload, signal
    },
      options);
    }




export const getUpdateTrimHistoryMutationOptions = <TError = AppErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTrimHistory>>, TError,{data: UpdateTrimHistoryPayload}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof updateTrimHistory>>, TError,{data: UpdateTrimHistoryPayload}, TContext> => {

const mutationKey = ['updateTrimHistory'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTrimHistory>>, {data: UpdateTrimHistoryPayload}> = (props) => {
          const {data} = props ?? {};

          return  updateTrimHistory(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateTrimHistoryMutationResult = NonNullable<Awaited<ReturnType<typeof updateTrimHistory>>>
    export type UpdateTrimHistoryMutationBody = UpdateTrimHistoryPayload
    export type UpdateTrimHistoryMutationError = AppErrorResponse

    export const useUpdateTrimHistory = <TError = AppErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTrimHistory>>, TError,{data: UpdateTrimHistoryPayload}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateTrimHistory>>,
        TError,
        {data: UpdateTrimHistoryPayload},
        TContext
      > => {
      return useMutation(getUpdateTrimHistoryMutationOptions(options), queryClient);
    }

export const getTrimSnapshots = (

 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {


      return customAxios<UpdateTrimSnapshotsPayload>(
      {url: `/api/settings/trim_snapshots`, method: 'GET', signal
    },
      options);
    }




export const getGetTrimSnapshotsQueryKey = () => {
    return [
    `/api/settings/trim_snapshots`
    ] as const;
    }


export const getGetTrimSnapshotsQueryOptions = <TData = Awaited<ReturnType<typeof getTrimSnapshots>>, TError = AppErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTrimSnapshots>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTrimSnapshotsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTrimSnapshots>>> = ({ signal }) => getTrimSnapshots(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTrimSnapshots>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTrimSnapshotsQueryResult = NonNullable<Awaited<ReturnType<typeof getTrimSnapshots>>>
export type GetTrimSnapshotsQueryError = AppErrorResponse


export function useGetTrimSnapshots<TData = Awaited<ReturnType<typeof getTrimSnapshots>>, TError = AppErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTrimSnapshots>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTrimSnapshots>>,
          TError,
          Awaited<ReturnType<typeof getTrimSnapshots>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTrimSnapshots<TData = Awaited<ReturnType<typeof getTrimSnapshots>>, TError = AppErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTrimSnapshots>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTrimSnapshots>>,
          TError,
          Awaited<ReturnType<typeof getTrimSnapshots>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTrimSnapshots<TData = Awaited<ReturnType<typeof getTrimSnapshots>>, TError = AppErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTrimSnapshots>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetTrimSnapshots<TData = Awaited<ReturnType<typeof getTrimSnapshots>>, TError = AppErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTrimSnapshots>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTrimSnapshotsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const updateTrimSnapshots = (
    updateTrimSnapshotsPayload: UpdateTrimSnapshotsPayload,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {


      return customAxios<UpdateTrimSnapshots200>(
      {url: `/api/settings/trim_snapshots`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateTrimSnapshotsPayload, signal
    },
      options);
    }




export const getUpdateTrimSnapshotsMutationOptions = <TError = AppErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTrimSnapshots>>, TError,{data: UpdateTrimSnapshotsPayload}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof updateTrimSnapshots>>, TError,{data: UpdateTrimSnapshotsPayload}, TContext> => {

const mutationKey = ['updateTrimSnapshots'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTrimSnapshots>>, {data: UpdateTrimSnapshotsPayload}> = (props) => {
          const {data} = props ?? {};

          return  updateTrimSnapshots(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateTrimSnapshotsMutationResult = NonNullable<Awaited<ReturnType<typeof updateTrimSnapshots>>>
    export type UpdateTrimSnapshotsMutationBody = UpdateTrimSnapshotsPayload
    export type UpdateTrimSnapshotsMutationError = AppErrorResponse

    export const useUpdateTrimSnapshots = <TError = AppErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTrimSnapshots>>, TError,{data: UpdateTrimSnapshotsPayload}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateTrimSnapshots>>,
        TError,
        {data: UpdateTrimSnapshotsPayload},
        TContext
      > => {
      return useMutation(getUpdateTrimSnapshotsMutationOptions(options), queryClient);
    }

export const getSnapshot = (
    id: string,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {


      return customAxios<Blob>(
      {url: `/api/snapshot/${id}`, method: 'GET',
        responseType: 'blob', signal
    },
      options);
    }




export const getGetSnapshotQueryKey = (id: string,) => {
    return [
    `/api/snapshot/${id}`
    ] as const;
    }


export const getGetSnapshotQueryOptions = <TData = Awaited<ReturnType<typeof getSnapshot>>, TError = AppErrorResponse>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSnapshot>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSnapshotQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSnapshot>>> = ({ signal }) => getSnapshot(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSnapshot>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSnapshotQueryResult = NonNullable<Awaited<ReturnType<typeof getSnapshot>>>
export type GetSnapshotQueryError = AppErrorResponse


export function useGetSnapshot<TData = Awaited<ReturnType<typeof getSnapshot>>, TError = AppErrorResponse>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSnapshot>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSnapshot>>,
          TError,
          Awaited<ReturnType<typeof getSnapshot>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSnapshot<TData = Awaited<ReturnType<typeof getSnapshot>>, TError = AppErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSnapshot>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSnapshot>>,
          TError,
          Awaited<ReturnType<typeof getSnapshot>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSnapshot<TData = Awaited<ReturnType<typeof getSnapshot>>, TError = AppErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSnapshot>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetSnapshot<TData = Awaited<ReturnType<typeof getSnapshot>>, TError = AppErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSnapshot>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSnapshotQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const mjpegStreamHandler = (

 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {


      return customAxios<number[]>(
      {url: `/api/stream`, method: 'GET', signal
    },
      options);
    }




export const getMjpegStreamHandlerQueryKey = () => {
    return [
    `/api/stream`
    ] as const;
    }


export const getMjpegStreamHandlerQueryOptions = <TData = Awaited<ReturnType<typeof mjpegStreamHandler>>, TError = AppErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof mjpegStreamHandler>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMjpegStreamHandlerQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof mjpegStreamHandler>>> = ({ signal }) => mjpegStreamHandler(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof mjpegStreamHandler>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MjpegStreamHandlerQueryResult = NonNullable<Awaited<ReturnType<typeof mjpegStreamHandler>>>
export type MjpegStreamHandlerQueryError = AppErrorResponse


export function useMjpegStreamHandler<TData = Awaited<ReturnType<typeof mjpegStreamHandler>>, TError = AppErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof mjpegStreamHandler>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof mjpegStreamHandler>>,
          TError,
          Awaited<ReturnType<typeof mjpegStreamHandler>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMjpegStreamHandler<TData = Awaited<ReturnType<typeof mjpegStreamHandler>>, TError = AppErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof mjpegStreamHandler>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof mjpegStreamHandler>>,
          TError,
          Awaited<ReturnType<typeof mjpegStreamHandler>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMjpegStreamHandler<TData = Awaited<ReturnType<typeof mjpegStreamHandler>>, TError = AppErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof mjpegStreamHandler>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useMjpegStreamHandler<TData = Awaited<ReturnType<typeof mjpegStreamHandler>>, TError = AppErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof mjpegStreamHandler>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMjpegStreamHandlerQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getUsers = (

 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {


      return customAxios<UserResponse[]>(
      {url: `/api/users`, method: 'GET', signal
    },
      options);
    }




export const getGetUsersQueryKey = () => {
    return [
    `/api/users`
    ] as const;
    }


export const getGetUsersQueryOptions = <TData = Awaited<ReturnType<typeof getUsers>>, TError = void | AppErrorResponse | string>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUsersQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsers>>> = ({ signal }) => getUsers(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getUsers>>>
export type GetUsersQueryError = void | AppErrorResponse | string


export function useGetUsers<TData = Awaited<ReturnType<typeof getUsers>>, TError = void | AppErrorResponse | string>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsers>>,
          TError,
          Awaited<ReturnType<typeof getUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsers<TData = Awaited<ReturnType<typeof getUsers>>, TError = void | AppErrorResponse | string>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsers>>,
          TError,
          Awaited<ReturnType<typeof getUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsers<TData = Awaited<ReturnType<typeof getUsers>>, TError = void | AppErrorResponse | string>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUsers<TData = Awaited<ReturnType<typeof getUsers>>, TError = void | AppErrorResponse | string>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUsersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const createUser = (
    createUserPayload: CreateUserPayload,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {


      return customAxios<UserResponse>(
      {url: `/api/users`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createUserPayload, signal
    },
      options);
    }




export const getCreateUserMutationOptions = <TError = AppErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUser>>, TError,{data: CreateUserPayload}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof createUser>>, TError,{data: CreateUserPayload}, TContext> => {

const mutationKey = ['createUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createUser>>, {data: CreateUserPayload}> = (props) => {
          const {data} = props ?? {};

          return  createUser(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateUserMutationResult = NonNullable<Awaited<ReturnType<typeof createUser>>>
    export type CreateUserMutationBody = CreateUserPayload
    export type CreateUserMutationError = AppErrorResponse

    export const useCreateUser = <TError = AppErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUser>>, TError,{data: CreateUserPayload}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createUser>>,
        TError,
        {data: CreateUserPayload},
        TContext
      > => {
      return useMutation(getCreateUserMutationOptions(options), queryClient);
    }

export const deleteUser = (
    id: number,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {


      return customAxios<void>(
      {url: `/api/users/${id}`, method: 'DELETE', signal
    },
      options);
    }




export const getDeleteUserMutationOptions = <TError = AppErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUser>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteUser(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteUserMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUser>>>

    export type DeleteUserMutationError = AppErrorResponse

    export const useDeleteUser = <TError = AppErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteUser>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteUserMutationOptions(options), queryClient);
    }

export const changePassword = (
    id: number,
    changePasswordPayload: ChangePasswordPayload,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {


      return customAxios<void>(
      {url: `/api/users/${id}/password`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: changePasswordPayload, signal
    },
      options);
    }




export const getChangePasswordMutationOptions = <TError = AppErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changePassword>>, TError,{id: number;data: ChangePasswordPayload}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof changePassword>>, TError,{id: number;data: ChangePasswordPayload}, TContext> => {

const mutationKey = ['changePassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof changePassword>>, {id: number;data: ChangePasswordPayload}> = (props) => {
          const {id,data} = props ?? {};

          return  changePassword(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ChangePasswordMutationResult = NonNullable<Awaited<ReturnType<typeof changePassword>>>
    export type ChangePasswordMutationBody = ChangePasswordPayload
    export type ChangePasswordMutationError = AppErrorResponse

    export const useChangePassword = <TError = AppErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changePassword>>, TError,{id: number;data: ChangePasswordPayload}, TContext>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof changePassword>>,
        TError,
        {id: number;data: ChangePasswordPayload},
        TContext
      > => {
      return useMutation(getChangePasswordMutationOptions(options), queryClient);
    }

export const websocketHandler = (
    params: WebsocketHandlerParams,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {


      return customAxios<unknown>(
      {url: `/api/ws`, method: 'GET',
        params, signal
    },
      options);
    }




export const getWebsocketHandlerQueryKey = (params?: WebsocketHandlerParams,) => {
    return [
    `/api/ws`, ...(params ? [params] : [])
    ] as const;
    }


export const getWebsocketHandlerQueryOptions = <TData = Awaited<ReturnType<typeof websocketHandler>>, TError = void | AppErrorResponse>(params: WebsocketHandlerParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof websocketHandler>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWebsocketHandlerQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof websocketHandler>>> = ({ signal }) => websocketHandler(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof websocketHandler>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type WebsocketHandlerQueryResult = NonNullable<Awaited<ReturnType<typeof websocketHandler>>>
export type WebsocketHandlerQueryError = void | AppErrorResponse


export function useWebsocketHandler<TData = Awaited<ReturnType<typeof websocketHandler>>, TError = void | AppErrorResponse>(
 params: WebsocketHandlerParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof websocketHandler>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof websocketHandler>>,
          TError,
          Awaited<ReturnType<typeof websocketHandler>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWebsocketHandler<TData = Awaited<ReturnType<typeof websocketHandler>>, TError = void | AppErrorResponse>(
 params: WebsocketHandlerParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof websocketHandler>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof websocketHandler>>,
          TError,
          Awaited<ReturnType<typeof websocketHandler>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWebsocketHandler<TData = Awaited<ReturnType<typeof websocketHandler>>, TError = void | AppErrorResponse>(
 params: WebsocketHandlerParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof websocketHandler>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useWebsocketHandler<TData = Awaited<ReturnType<typeof websocketHandler>>, TError = void | AppErrorResponse>(
 params: WebsocketHandlerParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof websocketHandler>>, TError, TData>>, request?: SecondParameter<typeof customAxios>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getWebsocketHandlerQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
